RealSurfLab/Controllers/FeedController.cs
using RealSurfLab.DAL;
using RealSurfLab.Helpers;
using RealSurfLab.Models.DBModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RealSurfLab.Controllers
{
    public class FeedController : Controller
    {
        private SurfDbContext dbContext = new SurfDbContext();
        // GET: Feed
        public ActionResult Index()
        {

            var posts = dbContext.Posts.OrderByDescending(c=>c.Id).ToList();
            ViewBag.Posts = posts;


            return View();
        }
        [HttpPost]
        public ActionResult AddPost(Post model, HttpPostedFileBase imageData)
        {

            if (imageData == null && model.Text == null)
            {
                ModelState.AddModelError(string.Empty, "Не загружено изображение или отсутствует текст");
                var postsInDb = dbContext.Posts.OrderByDescending(c => c.Id).ToList();
                ViewBag.Posts = postsInDb;
                return View("Index");
            }


            model.PublishDate = DateTime.Now;


            if (imageData != null)
            {
                model.Photo = ImageSaveHelper.SaveImage(imageData);
            }

            var userId = Convert.ToInt32(Session["UserId"]);
            var userInDb = dbContext.Users.FirstOrDefault(c => c.Id == userId);

            model.Author = userInDb;

            dbContext.Posts.Add(model);

            dbContext.SaveChanges();

            var posts = dbContext.Posts.OrderByDescending(c => c.Id).ToList();
            ViewBag.Posts = posts;
            return View("Index");
        }

    }
}

RealSurfLab/Views/Feed/Index.cshtml
@using RealSurfLab.Models.DBModels
@model RealSurfLab.Models.DBModels.Post
@{
    ViewBag.Title = "Index";
}

@if (Session["UserId"] != null)
{

    using (Html.BeginForm("AddPost", "Feed", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <form>
            <div class="panel panel-info">
                <div class="panel-heading">
                    Добавление новой записи<br>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                </div>
                <div class="panel-body">
                    @Html.LabelFor(model => model.Text)<br>
                    @Html.TextAreaFor(model => model.Text, 10, 100, new { htmlAttributes = new { @class = "form-control" } })<br>

                    @Html.LabelFor(model => model.Photo)
                    <input name="imageData" type="file" accept="image/jpg" />


                    <button type="submit" class="btn">Добавить</button>

                </div>
            </div>
        </form>
    }
}

    @foreach (var post in ViewBag.Posts)
    {

        <div class="panel panel-info">
            <div class=" panel-heading">
                @{ 
                    var photoUrl = RealSurfLab.Helpers.ImageUrlHelper.GetUrl(post.Author.Photo);
                    if(photoUrl !=null)
                    {
                        <img class="" src="@Url.Content(photoUrl)" height="25" />
                    }
                }



                @post.Author.Nickname
                <br>
                @post.PublishDate
            </div>
            <div class="panel-body">
                <p>@post.Text</p>

                @if (@post.Photo != Guid.Empty)
                {
                    var url = string.Format("~/Content/Images/Uploads/{0}.jpg", @post.Photo.ToString());
                    <img src=@Url.Content(url) class = "full-width">
                }
            </div>


        </div>



    }